### ISSUE TITLE
List normal snippets as well

### ISSUE THREAD

**Issue by languitar** [ncm2/ncm2-ultisnips#3]
Would be nice if this plugin could also act as a normal source to ncm2 for listing available snippets (not the ones from the language server).

**Comment by roxma** [comment]
It does.,

But with current impl, it only list the snippets after 3 charaters is typed. You could override it.

**Comment by languitar** [comment]
Then this doesn't work here. For instance, in python I have a snippet with trigger `class`. I don't get any completion for this, even after typing `cla` or `clas`.

**Comment by clason** [comment]
I do get autocomplete of snippets; the only thing I'm missing is the description of the snippets:

![ncm2](https://user-images.githubusercontent.com/2361214/42630195-375e8800-85d6-11e8-97f1-e06159e24801.png)
(ncm2)

![deoplete](https://user-images.githubusercontent.com/2361214/42630190-2f4446aa-85d6-11e8-9211-6fb36b4f09df.png)
(deoplete)

**Comment by languitar** [comment]
![2018-07-12t13 20 54 02 00](https://user-images.githubusercontent.com/1336287/42631533-c157cedc-85da-11e8-940a-f8924fc1abb8.png)

This is what I get. Nothing from ultisnips. What can I do to provide debugging information?

**Comment by clason** [comment]
Wow, that was fast! Works like a charm, thank you!

**Comment by languitar** [comment]
Thanks, now it works :)
