### ISSUE TITLE
Show all UltiSnips completion

### ISSUE THREAD

**Issue by filipekiss** [ncm2/ncm2-ultisnips#7]
With NCM I could trigger `cm_refresh` to show available completions at current cursor position and all available snippets would be listed.

Is this possible with NCM2?

Thanks!

**Comment by roxma** [comment]
Not possible with current version.

**Comment by roxma** [comment]
`inoremap <your-key> <c-r>=ncm2#force_trigger('ultisnips')<cr>`

**Comment by filipekiss** [comment]
Thanks @roxma!
