### ISSUE TITLE
Compatible issues with auto-pairs

### ISSUE THREAD

**Issue by xu-cheng** [ncm2/ncm2-ultisnips#9]
Hi, thanks for the plugin. I wonder if there is a possibility to make this plugin to be compatible with [auto-pairs](https://github.com/jiangmiao/auto-pairs/)

Some related information can be found at:
* https://github.com/jiangmiao/auto-pairs/issues/91#issuecomment-241692588
* https://github.com/jiangmiao/auto-pairs/issues/16

However I am not sure what the equivalent keymap for `ncm2-ultisnips` should be.

**Comment by smutch** [comment]
I'm not sure if this is just specific to my config, but I was able to get things working with:

```
inoremap <silent> <expr> <CR> ncm2_ultisnips#expand_or("\<CR>\<C-R>=AutoPairsReturn()<CR>", 'n')
```

This solution has had minimal testing on my part and may not work in all situations though...

**Comment by roxma** [comment]
Duplicated https://github.com/ncm2/ncm2/issues/129
